import fs from "node:fs";
import path from "node:path";

const root = process.cwd();
const requiredFiles = [
  ".github/workflows/validate.yml",
  "README.md",
  "LICENSE",
  "NOTICE",
  "ADDITIONAL_TERMS.md",
  "PRIVACY.md",
  "SECURITY.md",
  "TRADEMARKS.md",
  "docs/CHROME_WEB_STORE.md",
  "docs/RELEASE_NOTES_v0.2.1.md",
  "manifest.json",
  "assets/icons/icon-16.png",
  "assets/icons/icon-32.png",
  "assets/icons/icon-48.png",
  "assets/icons/icon-128.png",
  "src/background/service-worker.js",
  "src/content/content.js",
  "src/print/print.html",
  "src/print/print.css",
  "src/print/print.js",
  "src/popup/popup.html",
  "src/popup/popup.css",
  "src/popup/popup.js"
];

for (const file of requiredFiles) {
  assert(fs.existsSync(path.join(root, file)), `Missing ${file}`);
}

const manifest = JSON.parse(fs.readFileSync(path.join(root, "manifest.json"), "utf8"));
const packageJson = JSON.parse(fs.readFileSync(path.join(root, "package.json"), "utf8"));
assert(packageJson.license === "AGPL-3.0-only", "package.json must declare AGPL-3.0-only");
assert(manifest.manifest_version === 3, "Manifest must use MV3");
assert(manifest.name === "CF Gyms Statement Exporter", "Unexpected extension name");
assert(manifest.homepage_url === "https://icpcassiut.org", "Missing ICPC Assiut homepage URL");
assert(manifest.permissions.includes("debugger"), "Manifest must request debugger permission");
assert(manifest.permissions.includes("downloads"), "Manifest must request downloads permission");
assert(manifest.permissions.includes("storage"), "Manifest must request storage permission");
assert(!manifest.permissions.includes("scripting"), "Manifest must not request unused scripting permission");
assert(manifest.host_permissions.includes("https://codeforces.com/*"), "Missing Codeforces host permission");
assert(manifest.content_scripts[0].matches.includes("https://codeforces.com/*"), "Missing Codeforces content script match");
assert(manifest.icons?.["128"] === "assets/icons/icon-128.png", "Missing 128px icon");

const content = fs.readFileSync(path.join(root, "src/content/content.js"), "utf8");
for (const pattern of [
  "/^\\/contest\\/(\\d+)\\/problems$/",
  "/^\\/gym\\/(\\d+)\\/problems$/",
  "/^\\/group\\/([^/]+)\\/contest\\/(\\d+)\\/problems$/",
  "document.querySelectorAll(\".problem-statement\")",
  "CF_CAPTURE_START_EXPORT_FROM_PAGE"
]) {
  assert(content.includes(pattern), `Content script missing ${pattern}`);
}

const popup = fs.readFileSync(path.join(root, "src/popup/popup.js"), "utf8");
for (const token of [
  "Reload this Codeforces problemset page",
  "/^\\/contest\\/\\d+\\/problems$/",
  "/^\\/gym\\/\\d+\\/problems$/",
  "/^\\/group\\/[^/]+\\/contest\\/\\d+\\/problems$/"
]) {
  assert(popup.includes(token), `Popup missing ${token}`);
}

const background = fs.readFileSync(path.join(root, "src/background/service-worker.js"), "utf8");
for (const token of [
  "Page.printToPDF",
  "chrome.debugger, \"attach\"",
  "chrome.downloads, \"download\"",
  "CF_CAPTURE_PRINT_READY",
  "cleanupStaleExportSessions",
  "EXPORT_SESSION_TTL_MS"
]) {
  assert(background.includes(token), `Background missing ${token}`);
}

const printCss = fs.readFileSync(path.join(root, "src/print/print.css"), "utf8");
for (const token of ["@page", "break-before: page", "break-inside: avoid"]) {
  assert(printCss.includes(token), `Print CSS missing ${token}`);
}

const privacy = fs.readFileSync(path.join(root, "PRIVACY.md"), "utf8");
for (const token of ["does not collect", "chrome.storage.local", "does not make analytics"]) {
  assert(privacy.includes(token), `Privacy policy missing ${token}`);
}

const additionalTerms = fs.readFileSync(path.join(root, "ADDITIONAL_TERMS.md"), "utf8");
for (const token of ["AGPL-3.0-only", "Generated by icpcassiut.org", "AGPLv3 Section 7"]) {
  assert(additionalTerms.includes(token), `Additional terms missing ${token}`);
}

const trademarks = fs.readFileSync(path.join(root, "TRADEMARKS.md"), "utf8");
for (const token of ["ICPC Assiut", "icpcassiut.org", "No Trademark License"]) {
  assert(trademarks.includes(token), `Trademark policy missing ${token}`);
}

const workflow = fs.readFileSync(path.join(root, ".github/workflows/validate.yml"), "utf8");
for (const token of ["npm run build:icons", "npm run check", "npm run package", "cf-gyms-statement-exporter", "actions/upload-artifact"]) {
  assert(workflow.includes(token), `Validate workflow missing ${token}`);
}

const storePrep = fs.readFileSync(path.join(root, "docs/CHROME_WEB_STORE.md"), "utf8");
for (const token of ["Permission Justification", "Privacy Disclosure", "Required Screenshots"]) {
  assert(storePrep.includes(token), `Chrome Web Store doc missing ${token}`);
}

console.log("Smoke check passed");

function assert(condition, message) {
  if (!condition) {
    throw new Error(message);
  }
}
